# Lists

**Creating a list**:

```python
my_list = [2, 6, 9, 12]
data = ["hello", "world", "!"]
```

**Modifying lists**:

```python
nums = [42, 100]

nums.append(8)
nums.insert(0, 200)
nums.append(51)

print(nums)
```

**Accessing list elements**:

```python
nums = [4, 78, 3, 9]

print(nums[2])
print(nums[-1])

```

**Concatenating Lists**:

```python
left = [1, 2, 3]
right = [4, 5, 6]

new = left + right
print(new)
```

**Removing items from Lists**:

```python
data = [4, 8, 12, 16, 20]

num1 = data.pop(2)
num2 = data.pop(-2)

print(data)

```

**Iterating Lists**:

1) Index-iteration

```python
nums = [10, 20, 30, 40]

for i in range(len(nums)):
   print(nums[i])
```

2) For-each loop

```python
nums = [10, 20, 30, 40]

for num in nums:
   print(num)
```


#### Ex 7.0

You are given:
* The list `data` containing integers `[4, 8, 12, 16]`.
* An empty list `doubles`.

Write a program that follows the following steps, what is the output of this program?
1. You a **for-each** loop to add the double of each number from `data` to the `doubles` list.
1. Remove the last element from `doubles` and assign it to a variable `elem`
1. Append the first element of `data` to the end of `doubles`.
1. Insert `elem` as the second element of `doubles`
1. Print the final `doubles` list.

In [ ]:
data = [4, 8, 12, 16]
doubles = []

# 1
for _________:
    _________

# 2
_________ = _________

# 3
_________

# 4
_________

# 5
_________

#### Ex 7.0.1 (Extension!)

Use the original `data` list: [4, 8, 12, 16].

6. Create a new list `special_numbers`, the list should be created empty.
1. Add to `special_numbers` the triple of each number from `data`, but only if the number is divisible by 4.
1. Replace the second element in `special_numbers` with the sum of the first and last elements of `data`.
1. Print the final special_numbers list.

___

# Dictionaries

**Creating a dictionary**:

```python
nums = {"num1": 42, "num2": 100, "num3": 8}
data = {"foo": 8.2, 100: "bar"}

print(nums)
print(data)
```

**Accessing dictionary elements**:

```python
heights = {"Charles": 175, "Adam": 160, "Florence": 180}

print(heights["Adam"])
print(heights["Florence"])
```

**Modifying dictionaries**:

```python
data = {"a": 42, "b": 3}


# Adding new keys:
data["c"] = 800
data["d"] = 4.5
print(data)

# Modifying values of existing keys:
data["a"] = 10
data["b"] = 3.2
print(data)

```

**Deleting dictionary entries**:

```python
data = {"a": 42, "b": 3, "c": 100}

del data["a"]
del data["c"]
print(data)
```

**Iterating Dictionaries**:

1) Key-iteration

```python
data = {"a": 4, "f": 1, "z": 8}

for key in data:
   value = data[key]
   print(key, value)
```

2) For-each loop

```python
data = {"a": 4, "f": 1, "z": 8}

for key, value in data.items():
  print(key, value)
```

___

#### Ex 7.1

Write a program given a dictionary named `gifts` with keys as names and gifts as values: 

```gifts = {"Alice": "Teddy Bear", "Bob": "Train Set", "Eve": "Doll"}```
1. Adds a new entry with `"Charlie"` as the key and `"Book"` as the value.
1. Changes `"Eve"`'s gift to `"Bicycle"`.
1. Removes `"Bob"` from the dictionary.
1. Using a for-each dictionary loop, iterates over `gifts` and print each name and their corresponding gift in the format `"Name: Gift"`.
1. Prints the final output dictionary `gifts`

In [ ]:
gifts = {"Alice": "Teddy Bear", "Bob": "Train Set", "Eve": "Doll"}

# 1
_________ = _________

# 2
_________ = _________

# 3
_________

# 4
for _________:
    _________

# 5
_________

#### Ex 7.1.1 (Extension!)

Start with the same dictionary `gifts` from Ex 7.1: `{"Alice": "Teddy Bear", "Charlie": "Book", "Eve": "Bicycle"}`.

6. Create a new dictionary empty dictionary `updated_gifts`.
1. Using a for-each loop, for each entry, if the gift is not `"Book"`, replace the gift with `"Surprise Gift"`.
1. Add a new key `"Dave"` with the gift `"Socks"`.
1. Print the `updated_gifts` dictionary.

___

# Sets


**Creating a set**:

```python
nums = {42, 100, 42}
data = {"A", "C", "D"}

print(nums)
print(data)
```

**Add elements to a set**:

```python
nums = {42, 100}

nums.add(8)
```

**Remove elements from a set**:

```python
nums = {42, 100}

nums.remove(100)
```

**Set Theory**:

```python
set1 = {"A", "B", "C"}
set2 = {"B", "C", "D"}

# Union:
print(set1 | set2)

# Intersection
print(set1 & set2)

# Difference
print(set1 - set2)
```

___

#### Ex 7.2

Given two sets: `set_a` with the numbers `{1, 2, 3}` and `set_b` with `{3, 4, 5}`.

1. Add the number `6` to both `set_a` and to `set_b`
1. Removing the number `1` from `set_a`.
1. Form a new set `u_set` that combines all elements from both `set_a` and `set_b`.
1. Now, create `i_set` that contains only elements common to both `set_a` and `set_b`.
1. Next, make `d_set` that has elements in `set_a` but not in `set_b`.
1. Print `u_set`, `i_set`, and `d_set`.

In [ ]:
set_a = {1, 2, 3}
set_b = {3, 4, 5}

# 1
_________
_________

# 2
_________

# 3
u_set = _________

# 4
i_set = _________

# 5
d_set = _________

# 6
_________
_________
_________

#### Ex 7.2.1 (Extension!)

Start with the same sets `set_a` and `set_b` of Ex 7.2.

7. Find the `s_set` which includes the "symmetric difference", i.e. elements unique to each set (thus elements only in `set_a` and elements only in `set_b`.
2. Construct the "complement set" `c_set` containing elements in the combined `set_a` and `set_b` but not in their intersection.
3. Print `s_set` and `c_set`.

___

**Iterating Sets**:

```python
nums = {40, 10, 30, 20}

for num in nums:
   print(num)
```

___

#### Ex 7.3

1. Create a set named `numbers` with elements `{1, 2, 3, 4, 5}`.
2. Iterate through `numbers` and print each number.

In [ ]:
# 1
_________

# 2
for _________:
    _________

___

#### Ex 7.4

Using a different list `numbers`, iterate through the list. In each iteration:
1. If the number is even add it to the set `even`.
2. If the number if odd add it to the set `odd`.
3. Print `even` and `odd`. Why are there no duplicates?

In [ ]:
numbers = [1, 2, 3, 2, 5, 2, 4, 1, 7, 6, 2, 0, 3, 15]
even = set()
odd = set()

# 1 & 2
for _________:
    if _________:
        _________
    else:
        _________

# 3
_________
_________

#### Ex 7.4.1 (Extension!)

4. Calculate and print the union of `even` and `odd` sets. Think about why the length is different from that of `numbers`.
1. Calculate and print the intersection of `even` and `odd` sets. Think about why it's empty.
1. Create a new set `multiples_of_four` and add the elements from `numbers` that are multiples of 4 (using a loop).
1. Print the difference between `even` and `multiples_of_four` sets. Why are they different?

___

**Data-Structure Membership**:

```python
# Check if item is in List:
data1 = ["a", "b", "c"]
x = "b"

print(x in data1)
```
```python
# Check if item is in Set:
data2 = {"a", "b", "c"}
y = "b"

print(y in data2)
```
```python
# Check if key is in Dictionary:
data3 = {"a": 10, "b": 20}
z = "b"

print(z in data3)
```

___
#### Ex 7.5

Given a set named `fruits` with elements `{"apple", "banana", "cherry"}`.

1. Check if `"apple"` is in the `fruits` set and print the result.
1. Check if `"orange"` is in the `fruits` set and print the result.

In [ ]:
fruits = {"apple", "banana", "cherry"}

print("Is apple in fruits?", _________)
print("Is orange in fruits?", _________)

___

#### Ex 7.6

1. Create a list `colors` with the elements `["red", "blue", "green"]`.
1. Create a set `primary_colors` with the elements `{"red", "yellow", "blue"}`.
1. Check if the `specific_color` variable is in both `colors` and `primary_colors`, and print the result.
1. Check if each element in `colors` is also in `primary_colors`. Print each color and whether it is a primary color.

In [ ]:
# 1
_________

# 2
_________

# 3
specific_color = "green"
print("Is " + specific_color + " in both colors and primary_colors?", _________)

# 4
for _________:
    print("Is " + _________ + " a primary color?", _________)

#### Ex 7.6.1 (Extension!)

Given the list `extended_colors = ["red", "blue", "green", "orange", "purple"]` and the original `primary_colors` defined in Ex 7.6:

5. Check if each element in `extended_colors` is also in `primary_colors`. Print each color and whether it is a primary color.
1. Create a dictionary `color_categories` with two keys: `"primary"` and `"non_primary"`. Initialize each key with an empty list.
1. Iterate through `extended_colors`. For each color, add it to the appropriate list in `color_categories` based on whether it is in `primary_colors`.
1. Print the `color_categories` dictionary.

___
#### Ex 7.7

Given the two lists:
* `ist = ["Alice", "Bob", "Charlie", "Diana", "Ethan"]`
* `ism = {"Bob", "Diana", "Fiona", "George", "Hannah"}`

1. Check if each student in `ist` is also enrolled in ISM. If so, add them to a new set `common`.
1. Create a set `ism_only` which contains only the `ism` students that are not in the `common` set.
1. For each element in `ist`, using a loop, print if they are present in the `ism_only` set.

In [ ]:
ist = ["Alice", "Bob", "Charlie", "Diana", "Ethan"]
ism = {"Bob", "Diana", "Fiona", "George", "Hannah"}
common = set()

# 1
_________

# 2
_________

# 3
_________